### ISSUE TITLE
Doesn't working in Russia.

### ISSUE THREAD

**Issue by mrchermak** [SadeghHayeri/GreenTunnel#37]
**What's happened?**
I am living in Russia, Green Tunnel doesn't working, BUT GoodByeDPI is working. I use rutracker.org for example. My internet - [Beeline](https://en.wikipedia.org/wiki/PJSC_VimpelCom).

**Screenshots**
With GreenTunnel:
![Безымянный](https://user-images.githubusercontent.com/50665184/67548328-01ed0900-f71b-11e9-94df-348c8419a0dd.png)
With GoodbyeDPI:
![image](https://user-images.githubusercontent.com/50665184/67549276-50030c00-f71d-11e9-9c7a-6d0a928cc0a5.png)

**System Information**
 - OS: Windows 7.
 - Browser: Google Chrome.
 - Version: 77.0.3865.120

I tried open rutracker.org with GreenTunnel CLI, with GUI, doesn't working.

**Comment by AlexMak58** [comment]
A similar problem: #10

**Comment by F0restonn** [comment]
Green Tunnel just uses HTTPS over DNS, thus it bypasses blocking at the DNS server level, not IP addresses, if your provider blocked the site at the IP address level, then Green Tunnel will not help you, then you need to use proxies or connect to the remote the server

P.S Do you generally read the description?

**Comment by jasonliul** [comment]
A easy way is force Green Tunnel through upstream proxy, such as proxycap.
Green Tunnel isn't proxy program, you can get full speed.

**Comment by pcr910303** [comment]
@F0restonn 
> Green Tunnel just uses HTTPS over DNS

GreenTunnel isn't just DoH (BTW, it's DoH, not HoD), it acts as a local proxy server that also happens to resolve IP addresses with DoH for you. In particular, it splits & mangles TCP packets so that blocking is harder.

As you say, if the IP address is blocked by the provider, GreenTunnel can't help; however this is not the case as GoodbyeDPI works with the site (as GreenTunnel is basically GoodbyeDPI implemented in user space). Which means that if additional information of how GoodbyeDPI is 'unblocking' the site is given, GreenTunnel can implement the same thing too.

P.S Don't try to dismiss people, especially when you're not an expert and you also didn't read [the descriptions](https://github.com/SadeghHayeri/GreenTunnel#faq).
